### PR TITLE
Report pipeline investigation

### PR DESCRIPTION
**Pull request by Rob192**
Hello, this is the report for our sprint in january, feel free to comment/modify !

### CODE REVIEW

**Comment by Rob192** [comment]
@psorianom and @giuliasantarsieri 
this report is ready for review + publication

**Comment by psorianom** [comment]
Seems legit! Thanks @Rob192 and @giuliasantarsieri :)

**Review by psorianom — APPROVED** [review]

**Comment by psorianom** [comment]
One thing though @Rob192 , what do you think about renaming the arborescence `docs/piaf/reader/sprint January/report_january.md` to `docs/piaf/reader/sprints/report_january.md` ?
And moving `docs/piaf/reader/sprint January/data/full_spf_squad.json` to `knowledge-base/docs/assets/piaf/full_spf_squad.json` ?
I do still have to add the automatic creation of the toc to the github actions script.

**Comment by Rob192** [comment]
@psorianom OK i removed the folder sprints and also removed the dataset as it might be confusing to create a copy of the previous dataset

**Comment by psorianom** [comment]
Top thank you @Rob192!

**Pull request merged**
