### PR TITLE
creation of a product definition beta.gouv like

### PR DESCRIPTION
**Pull request by guillim**

### CODE REVIEW

**Comment by psorianom** [comment]
Hello @guillim ,
Quick question, should we include in this document the methodology we are going to follow to adress the problématique you stated ?

**Comment by guillim** [comment]
It's not what beta.gouv recommends (I follow their manual https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/la-vie-dune-se/investigation/)

**Comment by psorianom** [comment]
> It's not what beta.gouv recommends (I follow their manual https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/la-vie-dune-se/investigation/)

yeah maybe the word methodology is not the correct one. I am not talking about "a scientific methodology" to solve the problem (even if their vision of the scientific method is quite cartoonish.. but that is not the point here), I meant stating "the plan of action we want to follow to solve the task at hand", or "what is the next step 1, step 2, step 3" to answer the question you ask in the "problematique". I cannot find in the document where it says explicitly that we should not write down a plan of action of such sort. 

Also, the chronologie (Étape 1 (mars - avril) : interviews) seems off?  Have we already had these interviews ? Are they over?

**Comment by guillim** [comment]
good catch, i forgot to change the dates on step 1

**Comment by guillim** [comment]
about the "statement" for the how to proceed, yeah I would be a good idea to write it down. Not sure what to put yet though. I have a call with Beta in 10min to clarify that. I need to read more "investigation" pages [from beta](https://beta.gouv.fr/startups/#investigation) to be confident on what to put.

On thing sure : this "product page" is meant to evolve week after week. It's a first milestone, but not the last version for sure

**Comment by psorianom** [comment]
I see. Thanks for your answers :) Ok, if it evolves then let's push it and work on it as needed.

**Review by psorianom — APPROVED** [review]

**Pull request merged**
